### ISSUE TITLE
how to handle multiple sources and licenses?

### ISSUE THREAD

**Issue by ventosus** [pidcodes/pidcodes.github.com#108]
For a single device, I have:

* different licenses for firmware and hardware (e.g. Artistic-2.0 and CERN OHL 1.2)
* several source repos (e.g. firmware_old, firmware_new, PCB1, PCB2, hardware1, hardware2).

How should I handle this in the index.md?

**Comment by Arachnid** [comment]
The license field is a text field, so feel free to list both licenses - such as "FooPL (Software), BarPL (Hardware)". For links, if you can link to a single page that links to the other repos, such as a Github repo page, that would be ideal.

**Comment by ventosus** [comment]
OK, got it, thanks.
