### ISSUE TITLE
Scaling indefinitely

### ISSUE THREAD

**Issue by EtchedPixels** [pidcodes/pidcodes.github.com#33]
Have you thought about allocating one of the spare identifiers to mean something like "The vendor name string for this product should be parsed and contains a '#' followed by a UUID in hex" so every obscure random weird widget has a way to bind at least on free operating systems without needing to take up a pidcodes identifier ?

At that point for open systems at least it ought to then scale near infinitely and without intervention

Alan

**Comment by Arachnid** [comment]
I've seen various suggestions to this effect, but have yet to see it implemented anywhere. If someone wants to write, say, a linux kernel module that implements this, I'll be glad to allocate a PID in the 0x0000-0x0FFF range to it.
