### ISSUE TITLE
all CAPS or all lower case for PIDS directories?

### ISSUE THREAD

**Issue by hvisage** [pidcodes/pidcodes.github.com#389]
The current directories aren't sorting nicely as some are caps, and some are lower case. 

Would a all caps/lowercase pull request be accepted?

**Comment by hvisage** [comment]
see #390

**Comment by hvisage** [comment]
https://github.com/pidcodes/pidcodes.github.com/commit/15817c655d803e3c4af044b4c33dfd89237f06ed

:)

**Comment by Arachnid** [comment]
Thank you!
