### ISSUE TITLE
Can we help out approving code allocations?

### ISSUE THREAD

**Issue by jepler** [pidcodes/pidcodes.github.com#549]
Hi!  I'm a developer working on CircuitPython for Adafruit. I noticed that you've been unable to approve new codes for the past few months.  Would it be possible for me to help you out by reviewing these PRs to make sure they fit your guidelines?  Is there some other way I can help?

**Comment by tannewt** [comment]
Hi folks, I've begun merging PRs into a branch of my own. See #554 for the latest info.
