### ISSUE TITLE
[IMPORTANT] Open the project to new collaborators or reviewers

### ISSUE THREAD

**Issue by sabas1080** [pidcodes/pidcodes.github.com#557]
Hi @Arachnid 

We have seen this great project has stopped, we know that it may be too much work for one person to review so many projects, would you be willing to receive help or can we know if there is some other problem for which new projects have not been accepted?

@tannewt has offered his help (example pullrequest #554 ) and I can help too if you allow it

We look forward to getting a response from you.

regards

**Comment by tannewt** [comment]
Hey @sabas1080, I have heard back from @Arachnid and am working to help. If you need a PID for CircuitPython, we can merge in the PID if I've merged it into #554.

**Comment by sabas1080** [comment]
great!, thanks @tannewt
