### ISSUE TITLE
Website seems broken/incomplete

### ISSUE THREAD

**Issue by MrAureliusR** [pidcodes/pidcodes.github.com#568]
For example, my org is listed (FrozenElectronics), but the PID I was assigned (5555) is not. Some of the other entries are out of order; l0pthware's PIC32 board is at the very bottom of the list for me despite starting with a C. 

Not sure if this is because of the recent massive PR (thanks @tannewt and #554 !!!) but something is definitely a bit weird with the site.

**Comment by tannewt** [comment]
@MrAureliusR I'm not sure what caused the sorting issue. I believe your PID is broken because the file is missing a second `---` followed by a description. See others for an example.

**Comment by tannewt** [comment]
Looks like cb0b is last because it is lower case while the others are upper case. It'd be good to have it checked by the CI.

**Comment by MrAureliusR** [comment]
Alright, created PR #569 to try and resolve this :)

**Comment by tannewt** [comment]
Looks fixed! https://pid.codes/1209/5555/
