### ISSUE TITLE
New pull request failed

### ISSUE THREAD

**Issue by aR4chn1a** [pidcodes/pidcodes.github.com#579]
After the initial pull request for CombineReality (#555 ) failed because of extra website link and mismatching names (extra spaces) under org. We corrected the issue a few days after issue closed by moderator, but were no longer able to send anymore pull requests. How can we fix this?

**Comment by tannewt** [comment]
I've reopened the PR. I suspect a follow on PR didn't work because you were using the same source branch. Please get the CI passing on the PR and then I'll take another look.
