### ISSUE TITLE
VID/PID request for new board. 

### ISSUE THREAD

**Issue by GMDII** [pidcodes/pidcodes.github.com#606]
Hello. I was sent here from the adafruit circuitpython page. 

I am currently following this guide: https://learn.adafruit.com/how-to-add-a-new-board-to-circuitpython/overview

so that guide requires VID/PID in order to release the software.. but you require the software before i can get a VID/PID?  

so i dont know what to do.

**Comment by tannewt** [comment]
Hi @rfefx, please have a fork of CircuitPython with your board settings in it on GitHub. You can wait to PR to adafruit's CircuitPython until you have a pid.codes PID. Until you have one, you can use a pid.codes testing PID.
