### ISSUE TITLE
What is the actual license of this site: MIT or CC0?

### ISSUE THREAD

**Issue by jo-bitsch** [pidcodes/pidcodes.github.com#625]
There are two files in the main directory:
* [LICENSE](https://github.com/pidcodes/pidcodes.github.com/blob/7d2d9fc6fd6b57024ec155b98691b706f719636a/LICENSE) implying CC0
* [LICENSE.txt](https://github.com/pidcodes/pidcodes.github.com/blob/7d2d9fc6fd6b57024ec155b98691b706f719636a/LICENSE.txt) implying MIT

LICENSE.txt was commited one day after LICENSE. Both in the very early days of the repository. However, I don't seem to find documentation which one is actually in use.

Maybe this ist just a clean-up thing. Still it is a bit confusing. With the younger file being MIT license, I guess the intent is MIT, and to err on the side of compliance it's probably better to assume the more restrictive. Nevertheless, github's view license link on the right links to the CC0 version.

**Comment by Arachnid** [comment]
Good catch! The site is intended to be CC0 licensed. The MIT license comes from the Jekyll theme we're using. I've updated the license files in #626 to clarify this.
