### ISSUE TITLE
Pull requests taking forever

### ISSUE THREAD

**Issue by MentalMetalhead** [pidcodes/pidcodes.github.com#679]
Why are some pull requests that been waiting for awhile for reviews aren't getting reviewed but yet some coming in NEW are getting them in less than an hour or a day?

**Comment by tannewt** [comment]
I volunteer to administer this repo and get through PRs when I have the time and energy. Comments like this *don't* make me want to do this work.

If you need a PID urgently, then pay for one.

(I don't know why you are complaining. You've never opened a PR.)
