### ISSUE TITLE
htmlproofer 4.2.0 | Error:  invalid option: --internal-domains=pid.codes

### ISSUE THREAD

**Issue by bwshockley** [pidcodes/pidcodes.github.com#754]
It appears the options for the html proofer check are out of date for 4.2.0

This error happens when checking my PR #753 

"htmlproofer 4.2.0 | Error:  invalid option: --internal-domains=pid.codes" 

https://github.com/gjtorikian/html-proofer/compare/v4.1.0...v4.2.0

**Comment by bwshockley** [comment]
Appears that option "--internal-domains" was removed here:
https://github.com/gjtorikian/html-proofer/commit/7b0d193cf0796d7e722da3f65d7a47b8ba826a24

**Comment by tannewt** [comment]
Fixed by #761
